# ------------------------- Common ----------------------------
server.port=8090
spring.application.name=berte
spring.main.web-application-type=reactive
# ------------------------- Common -----------------------------

# ------------------------- Jackson ----------------------------
spring.jackson.default-property-inclusion=non_null
spring.jackson.deserialization.fail_on_unknown_properties=true
# ------------------------- Jackson ----------------------------

# --------------------------- i18n -----------------------------
spring.messages.basename=i18n/messages
# --------------------------- i18n -----------------------------

# ------------------------- Logging ----------------------------
app.logback.appenders=stdout
logging.level.org.springframework=INFO
logging.level.org.testcontainers=INFO
logging.level.com.github.dockerjava=WARN

logging.level.root=info
# ------------------------- Logging ----------------------------

# ------------------------ Scheduler ---------------------------
spring.quartz.properties.org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
spring.quartz.properties.org.quartz.jobStore.dataSource=quartzDataSource

spring.quartz.properties.org.quartz.dataSource.quartzDataSource.provider = hikaricp
spring.quartz.properties.org.quartz.dataSource.quartzDataSource.driver = org.postgresql.Driver
spring.quartz.properties.org.quartz.dataSource.quartzDataSource.user=berte
spring.quartz.properties.org.quartz.dataSource.quartzDataSource.password=berte
spring.quartz.properties.org.quartz.dataSource.quartzDataSource.maxConnections = 2

spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=never
spring.quartz.properties.org.quartz.jobStore.tablePrefix=berte.QRTZ_

spring.quartz.properties.org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
spring.quartz.properties.org.quartz.threadPool.threadCount=2

spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
# ------------------------ Scheduler ---------------------------

# -------------------------- Cache -----------------------------
spring.cache.jcache.config=classpath:ehcache.xml
# -------------------------- Cache -----------------------------

# -------------------------- JDBC ------------------------------
spring.r2dbc.schema=berte
spring.r2dbc.properties.schema=berte


# Properties for debugging database/sql issues
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
#logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
# -------------------------- JDBC ------------------------------


# -------------------------- Flyway -----------------------------
spring.flyway.enabled=true
spring.flyway.schemas=berte
# -------------------------- Flyway -----------------------------

# ------------------------- Actuator ----------------------------
management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=*
# also Actuator env InfoContributor is disabled by default
management.info.env.enabled=true
# ------------------------- Actuator ----------------------------

# ---------------------------- TLS ------------------------------
server.ssl.enabled=false
server.ssl.protocol=TLS
server.ssl.client-auth=none
server.ssl.key-store=classpath:certs/wss.p12
server.ssl.key-store-type=JKS
server.ssl.key-store-password=wsswss
server.ssl.key-alias=wss
server.ssl.trust-store=classpath:certs/wss.p12
server.ssl.trust-store-password=wsswss
# ---------------------------- TLS ------------------------------

spring.profiles.active=dev