version: '3.9'

services:
  berte:
    build: .
    container_name: berte
    depends_on:
      - db
    env_file:
      - ./src/main/resources/application-dev.properties
    ports:
      - "11006:11006"