# -------------------------- Data Source -----------------------------
spring.r2dbc.url=r2dbc:postgresql://localhost:5433/berte
spring.r2dbc.username=berte
spring.r2dbc.password=berte
# -------------------------- Data Source -----------------------------

# ---------------------------- Flyway --------------------------------
spring.flyway.url=jdbc:postgresql://localhost:5433/berte
spring.flyway.user=berte
spring.flyway.password=berte
# ---------------------------- Flyway --------------------------------

# ---------------------------- Logging -------------------------------
logging.level.root=info
# ---------------------------- Logging -------------------------------

# --------------------------- Scheduler ------------------------------
app.scheduling.enabled=true
spring.quartz.properties.org.quartz.dataSource.quartzDataSource.URL=jdbc:postgresql://localhost:5433/berte?schema=berte
# --------------------------- Scheduler ------------------------------

# ----------------------------- Berte --------------------------------
berte.user=user
# Rsocket
berte.rsocket.requester.uri=https://localhost:7000/rsocket
# JWT
berte.security.jwt.keystore.url=classpath:certs/jwk.p12
berte.security.jwt.keystore.password=classpath:certs/jwk.p12
berte.security.jwt.keystore.alias=classpath:certs/jwk.p12
berte.security.jwt.refresh-expiration= 86400000
berte.security.jwt.access-expiration= 86400000
# Security
berte.security.open=/login
# Cors
berte.security.cors.origins=*
berte.security.cors.methods=*
berte.security.cors.headers=*
berte.security.cors.allowCreds=true
berte.security.cors.age=864000
berte.security.cors.exposedHeaders=Authorization
# ----------------------------- Berte --------------------------------