#Datasource
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/berte
spring.r2dbc.username=berte
spring.r2dbc.schema=berte
spring.r2dbc.password=a12345678
spring.r2dbc.properties.schema=berte

spring.flyway.enabled=true
spring.flyway.user=berte
spring.flyway.password=a12345678
spring.flyway.url=jdbc:postgresql://localhost:5432/berte?schema=berte
spring.flyway.schemas=berte

spring.quartz.properties.org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
spring.quartz.properties.org.quartz.jobStore.dataSource=quartzDataSource

spring.quartz.properties.org.quartz.dataSource.quartzDataSource.provider = hikaricp
spring.quartz.properties.org.quartz.dataSource.quartzDataSource.driver = org.postgresql.Driver
spring.quartz.properties.org.quartz.dataSource.quartzDataSource.URL = jdbc:postgresql://localhost:5432/berte?schema=berte
spring.quartz.properties.org.quartz.dataSource.quartzDataSource.user = berte
spring.quartz.properties.org.quartz.dataSource.quartzDataSource.password = a12345678
spring.quartz.properties.org.quartz.dataSource.quartzDataSource.maxConnections = 2


# Spring quartz starter config
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=never
spring.quartz.properties.org.quartz.jobStore.tablePrefix=berte.QRTZ_

spring.quartz.properties.org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
spring.quartz.properties.org.quartz.threadPool.threadCount=2

spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO

spring.jpa.show-sql=true
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
