# -------------------------- Data Source -----------------------------
spring.r2dbc.url=r2dbc:postgresql://localhost:5433/berte
spring.r2dbc.username=berte
spring.r2dbc.password=berte
# -------------------------- Data Source -----------------------------

# ---------------------------- Flyway --------------------------------
spring.flyway.url=jdbc:postgresql://localhost:5433/berte
spring.flyway.user=berte
spring.flyway.password=berte
# ---------------------------- Flyway --------------------------------

# ---------------------------- Logging -------------------------------
logging.level.root=info
# ---------------------------- Logging -------------------------------

# --------------------------- Scheduler ------------------------------
app.scheduling.enabled=true
spring.quartz.properties.org.quartz.dataSource.quartzDataSource.URL=jdbc:postgresql://localhost:5433/berte?schema=berte
# --------------------------- Scheduler ------------------------------

# ------------------------------ App ---------------------------------
app.user=user
app.rsocket.requester.uri=https://localhost:7000/rsocket
# ------------------------------ App ---------------------------------